## Stock Price Prediction using Linear Regression

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import math
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
#conda install pip

In [3]:
#pip install quandl

##### Importing Dataset on Stock prices from www.quandl.com using quandl code of Apple Inc. 

In [4]:
import quandl

In [5]:
quandl.ApiConfig.api_key = "enter API code"        #enter API key

In [6]:
data = quandl.get("EOD/AAPL")
data

Open     High      Low    Close      Volume  Dividend  Split  \
Date                                                                         
2013-09-03  493.10  500.600  487.350  488.580  11854600.0       0.0    1.0   
2013-09-04  499.56  502.240  496.280  498.691  12322600.0       0.0    1.0   
2013-09-05  500.25  500.680  493.640  495.270   8441700.0       0.0    1.0   
2013-09-06  498.44  499.380  489.950  498.220  12840200.0       0.0    1.0   
2013-09-09  505.00  507.920  503.480  506.170  12167400.0       0.0    1.0   
...            ...      ...      ...      ...         ...       ...    ...   
2017-12-21  174.17  176.020  174.100  175.010  20949896.0       0.0    1.0   
2017-12-22  174.68  175.424  174.500  175.010  16349444.0       0.0    1.0   
2017-12-26  170.80  171.470  169.679  170.570  33185536.0       0.0    1.0   
2017-12-27  170.10  170.780  169.710  170.600  21498213.0       0.0    1.0   
2017-12-28  171.00  171.850  170.480  171.080  16480187.0       0.0    1.0   

             Adj_Open   Adj_High    Adj_Low  Adj_Close   Adj_Volume  
Date                                                                 
2013-09-03  15.619650  15.857223  15.437510  15.476472  331928800.0  
2013-09-04  15.824280  15.909173  15.720381  15.796753  345032800.0  
2013-09-05  15.846136  15.859757  15.636755  15.688388  236367600.0  
2013-09-06  15.788802  15.818578  15.519869  15.781833  359525600.0  
2013-09-09  15.996600  16.089095  15.948451  16.033661  340687200.0  
...               ...        ...        ...        ...          ...  
2017-12-21  41.899570  42.344619  41.882730  42.101646   83799584.0  
2017-12-22  42.022259  42.201241  41.978957  42.101646   65397776.0  
2017-12-26  41.088858  41.250038  40.819183  41.033528  132742144.0  
2017-12-27  40.920461  41.084047  40.826640  41.040745   85992852.0  
2017-12-28  41.136972  41.341454  41.011877  41.156217   65920748.0  

[1090 rows x 12 columns]

#### Meaningful features to get an insight into the future prices: High Low Percentage and Percentage Change

In [7]:
#High low Percentage
data['HL_PCT']= (data['Adj_High'] - data['Adj_Low'])/data['Adj_Close']*100
#Percentage Change
data['PCT_change']= (data['Adj_Close'] - data['Adj_Open'])/data['Adj_Open']*100

In [8]:
data

Open     High      Low    Close      Volume  Dividend  Split  \
Date                                                                         
2013-09-03  493.10  500.600  487.350  488.580  11854600.0       0.0    1.0   
2013-09-04  499.56  502.240  496.280  498.691  12322600.0       0.0    1.0   
2013-09-05  500.25  500.680  493.640  495.270   8441700.0       0.0    1.0   
2013-09-06  498.44  499.380  489.950  498.220  12840200.0       0.0    1.0   
2013-09-09  505.00  507.920  503.480  506.170  12167400.0       0.0    1.0   
...            ...      ...      ...      ...         ...       ...    ...   
2017-12-21  174.17  176.020  174.100  175.010  20949896.0       0.0    1.0   
2017-12-22  174.68  175.424  174.500  175.010  16349444.0       0.0    1.0   
2017-12-26  170.80  171.470  169.679  170.570  33185536.0       0.0    1.0   
2017-12-27  170.10  170.780  169.710  170.600  21498213.0       0.0    1.0   
2017-12-28  171.00  171.850  170.480  171.080  16480187.0       0.0    1.0   

             Adj_Open   Adj_High    Adj_Low  Adj_Close   Adj_Volume    HL_PCT  \
Date                                                                            
2013-09-03  15.619650  15.857223  15.437510  15.476472  331928800.0  2.711941   
2013-09-04  15.824280  15.909173  15.720381  15.796753  345032800.0  1.195129   
2013-09-05  15.846136  15.859757  15.636755  15.688388  236367600.0  1.421447   
2013-09-06  15.788802  15.818578  15.519869  15.781833  359525600.0  1.892738   
2013-09-09  15.996600  16.089095  15.948451  16.033661  340687200.0  0.877176   
...               ...        ...        ...        ...          ...       ...   
2017-12-21  41.899570  42.344619  41.882730  42.101646   83799584.0  1.097080   
2017-12-22  42.022259  42.201241  41.978957  42.101646   65397776.0  0.527970   
2017-12-26  41.088858  41.250038  40.819183  41.033528  132742144.0  1.050009   
2017-12-27  40.920461  41.084047  40.826640  41.040745   85992852.0  0.627198   
2017-12-28  41.136972  41.341454  41.011877  41.156217   65920748.0  0.800795   

            PCT_change  
Date                    
2013-09-03   -0.916650  
2013-09-04   -0.173953  
2013-09-05   -0.995502  
2013-09-06   -0.044138  
2013-09-09    0.231683  
...                ...  
2017-12-21    0.482287  
2017-12-22    0.188917  
2017-12-26   -0.134660  
2017-12-27    0.293945  
2017-12-28    0.046784  

[1090 rows x 14 columns]

##### New dataframe with the new features

In [9]:
new_data = data[['Adj_Close','Adj_Volume','HL_PCT','PCT_change']]
new_data.head()

Adj_Close   Adj_Volume    HL_PCT  PCT_change
Date                                                    
2013-09-03  15.476472  331928800.0  2.711941   -0.916650
2013-09-04  15.796753  345032800.0  1.195129   -0.173953
2013-09-05  15.688388  236367600.0  1.421447   -0.995502
2013-09-06  15.781833  359525600.0  1.892738   -0.044138
2013-09-09  16.033661  340687200.0  0.877176    0.231683

In [10]:
new_data.isna().sum()

Adj_Close     0
Adj_Volume    0
HL_PCT        0
PCT_change    0
dtype: int64

No NaN values found

In [11]:
out = 10 #days
new_data['Prediction'] = new_data[['Adj_Close']].shift(-out)
new_data

<ipython-input-11-4fed63cb739c>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['Prediction'] = new_data[['Adj_Close']].shift(-out)


Adj_Close   Adj_Volume    HL_PCT  PCT_change  Prediction
Date                                                                
2013-09-03  15.476472  331928800.0  2.711941   -0.916650   14.422914
2013-09-04  15.796753  345032800.0  1.195129   -0.173953   14.719406
2013-09-05  15.688388  236367600.0  1.421447   -0.995502   14.960780
2013-09-06  15.781833  359525600.0  1.892738   -0.044138   14.805882
2013-09-09  16.033661  340687200.0  0.877176    0.231683   15.541726
...               ...          ...       ...         ...         ...
2017-12-21  42.101646   83799584.0  1.097080    0.482287         NaN
2017-12-22  42.101646   65397776.0  0.527970    0.188917         NaN
2017-12-26  41.033528  132742144.0  1.050009   -0.134660         NaN
2017-12-27  41.040745   85992852.0  0.627198    0.293945         NaN
2017-12-28  41.156217   65920748.0  0.800795    0.046784         NaN

[1090 rows x 5 columns]

In [12]:
new_data.tail()

Adj_Close   Adj_Volume    HL_PCT  PCT_change  Prediction
Date                                                                
2017-12-21  42.101646   83799584.0  1.097080    0.482287         NaN
2017-12-22  42.101646   65397776.0  0.527970    0.188917         NaN
2017-12-26  41.033528  132742144.0  1.050009   -0.134660         NaN
2017-12-27  41.040745   85992852.0  0.627198    0.293945         NaN
2017-12-28  41.156217   65920748.0  0.800795    0.046784         NaN

In [13]:
new_data.isna().sum()

Adj_Close      0
Adj_Volume     0
HL_PCT         0
PCT_change     0
Prediction    10
dtype: int64

There are NaN values

#### Conversion to numpy array 

In [14]:
X = np.array(new_data.drop(['Prediction'],1))
X = X[:-out]
print(X)

[[ 1.54764725e+01  3.31928800e+08  2.71194073e+00 -9.16649767e-01]
 [ 1.57967529e+01  3.45032800e+08  1.19512885e+00 -1.73953079e-01]
 [ 1.56883878e+01  2.36367600e+08  1.42144689e+00 -9.95502249e-01]
 ...
 [ 4.15387189e+01  1.41095036e+08  2.37447154e+00  2.05082742e+00]
 [ 4.13053688e+01  7.76369200e+07  5.41059988e-01 -2.61399942e-01]
 [ 4.14424921e+01  9.52737880e+07  8.93945551e-01 -1.33333333e-01]]


In [15]:
y = np.array(new_data['Prediction']) 
y = y[:-out]
print(y)

[14.42291424 14.71940567 14.96078011 ... 41.03352802 41.04074503
 41.15621723]


##### Split the dataset into 80% training and 20% testing

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [17]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [18]:
print('Training Score: ', model.score(X_train,y_train))

print('Testing Score: ', model.score(X_test,y_test))

Training Score:  0.9697856711627835
Testing Score:  0.9673564285621605


In [19]:
y_pred = model.predict(X_test)
y_pred

array([34.53181298, 36.19176597, 36.59040074, 24.9529543 , 23.30819709,
       22.77412907, 16.00246916, 30.02761181, 17.66439255, 23.14080141,
       34.58601001, 27.72304554, 34.38085168, 17.43775101, 17.35217396,
       33.79962973, 26.63237348, 17.48663593, 26.3059722 , 22.90252166,
       22.19942237, 26.88078129, 29.41892201, 29.02801806, 20.63096108,
       25.69809621, 27.7033684 , 26.34192073, 29.62119861, 23.43717988,
       30.44687401, 29.58730205, 22.57993511, 25.24866155, 27.05892379,
       22.04527926, 25.65300983, 21.73162252, 24.97977377, 26.78991505,
       28.3507504 , 17.04944443, 25.04140948, 38.1907347 , 22.39117242,
       28.44644846, 25.25286471, 23.50647932, 22.78723607, 28.37901946,
       22.94952745, 22.05845896, 30.03793043, 22.6140906 , 20.50901117,
       17.17722578, 26.75024233, 29.97006825, 29.14828139, 26.19043083,
       27.04157451, 32.76006067, 24.78857158, 35.86379095, 25.61697223,
       37.09282978, 19.29095358, 18.49896938, 17.30197895, 39.99

#### Accuracy of the model

In [20]:
acc=metrics.r2_score(y_test,y_pred)
print("Accuracy Score of Model: ",round(acc*100,2),'%')

Accuracy Score of Model:  96.74 %


#### Actual Price and Predicted Price

In [21]:
prediction_df = pd.DataFrame({ 'Actual Price': y_test, 'Predicted Price': y_pred})  
prediction_df


Actual Price  Predicted Price
0       36.612849        34.531813
1       37.355242        36.191766
2       36.607500        36.590401
3       25.567636        24.952954
4       22.698773        23.308197
..            ...              ...
211     17.069376        18.162244
212     25.958297        25.402570
213     21.422237        22.167261
214     27.098525        25.535523
215     34.812219        34.797945

[216 rows x 2 columns]

#### Model evaluation

In [22]:
print('Mean Squared Error: ',mean_squared_error(y_test,y_pred))
print('Coefficient of determination: ',r2_score(y_test,y_pred))
print('Mean Squared Error: ',mean_absolute_error(y_test,y_pred))

Mean Squared Error:  1.4093826225709596
Coefficient of determination:  0.9673564285621605
Mean Squared Error:  0.9037260105509665


#### Forecasting

In [23]:
def predictor(forecast_days):
    
    
    # A variable for predicting 'n' days out into the future
    out = forecast_days
    new_data['Prediction'] = new_data[['Adj_Close']].shift(-out)
    
    # Convert the dataframe to a numpy array
    X = np.array(new_data.drop(['Prediction'],1))
    
    #Remove the last 'n' rows
    X = X[:-out]
    
    # Convert the dataframe to a numpy array 
    y = np.array(new_data['Prediction'])
    
    # Get all of the y values except the last '10' rows
    y = y[:-out]

    # Split the data into 80% training and 20% testing
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    # Create and train the Linear Regression  Model
    model = LinearRegression()
    
    # Train the model
    model.fit(X_train, y_train)

    # The best possible score is 1.0
    model_confidence = model.score(X_test, y_test)
    print('The Confidence {}\n'.format(model_confidence))
    
    # Set x_forecast equal to the last 10 rows of the original data set from Adj. Close column
    x_forecast = np.array(new_data.drop(['Prediction'],1))[-out:]

    
    # Print linear regression model predictions for the next '10' days
    model_prediction = model.predict(x_forecast)
    print('Prediction for next {} day price:\n {}'.format(forecast_days,model_prediction))

In [24]:
predictor(1)

The Confidence 0.996561622691355

Prediction for next 1 day price:
 [41.17987823]


<ipython-input-23-3d18060ccf91>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['Prediction'] = new_data[['Adj_Close']].shift(-out)


In [25]:
predictor(10)

The Confidence 0.9659452402746239

Prediction for next 10 day price:
 [41.66780109 42.08862428 42.67710533 42.22549707 42.17625274 42.33849018
 42.34142552 41.27004756 41.28155494 41.39477922]


<ipython-input-23-3d18060ccf91>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['Prediction'] = new_data[['Adj_Close']].shift(-out)
